version: "3.9"
services:
  backend:
    build: ../apps/backend
    ports: ["8000:8000"]

  frontend:
    build:
      context: ..
      dockerfile: apps/frontend/Dockerfile
    ports: ["8080:80"]
    depends_on: [backend]
