name: CD Staging
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            set -e
            export TAG=${{ github.sha}}
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            cd ~/pipeline-ci-cd-monorepo/deploy
            TAG=$TAG docker compose -f docker-compose.staging.yml pull
            TAG=$TAG docker compose -f docker-compose.staging.yml up -d --remove-orphans
            docker image prune -f